name: Update README
on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }} 
        with:
          template: README.md.tpl
          writeTo: README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update readme"
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
